# Generated by Django 6.0.1 on 2026-03-30 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harmonic_mean', models.IntegerField()),
                ('attempt_count', models.IntegerField()),
                ('valid_count', models.IntegerField()),
                ('test_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webgui.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('reaction_time', models.IntegerField()),
                ('attempt_result', models.IntegerField(choices=[(1, 'Valid'), (2, 'Too Early'), (3, 'Too Slow'), (4, 'No Response')])),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgui.testsession')),
            ],
        ),
    ]
